# Generated by Django 4.2.1 on 2024-01-08 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_setanothertype_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time',
            field=models.TimeField(default=datetime.time(1, 39, 49, 849114)),
        ),
        migrations.AlterField(
            model_name='setanothertype',
            name='exercise_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets4', to='tracker.exerciseworkout'),
        ),
        migrations.AlterField(
            model_name='setcyclingtraining',
            name='exercise_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets2', to='tracker.exerciseworkout'),
        ),
        migrations.AlterField(
            model_name='setstretching',
            name='exercise_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets3', to='tracker.exerciseworkout'),
        ),
        migrations.AlterField(
            model_name='setweighttraining',
            name='exercise_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets1', to='tracker.exerciseworkout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 9)),
        ),
    ]
