# Generated by Django 4.2.1 on 2024-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_setweighttraining_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseworkout',
            name='view',
            field=models.BooleanField(choices=[(True, 'Таблица'), (False, 'Сетка')], default=True, verbose_name='отображение подходов'),
        ),
    ]
