# Generated by Django 4.2.1 on 2024-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_exerciseworkout_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseworkout',
            name='view',
        ),
        migrations.AddField(
            model_name='workout',
            name='view',
            field=models.BooleanField(choices=[(True, 'Таблица'), (False, 'Сетка')], default=True, verbose_name='отображение подходов'),
        ),
    ]
