# Generated by Django 4.2.1 on 2024-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import workout.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categories by equipment',
                'verbose_name_plural': 'Categories by equipment',
            },
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categories by experience level',
                'verbose_name_plural': 'Categories by experience level',
            },
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Позиция')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workout.targetmuscle')),
            ],
            options={
                'verbose_name': 'Categories by target muscle group',
                'verbose_name_plural': 'Categories by target muscle group',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('start', models.TextField(blank=True, verbose_name='Исходное положение')),
                ('performing', models.TextField(blank=True, verbose_name='Исполнение')),
                ('variations', models.TextField(blank=True, verbose_name='Вариации')),
                ('remarks', models.TextField(blank=True, verbose_name='Примечания')),
                ('safety', models.TextField(blank=True, verbose_name='Безопасность')),
                ('additional', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('image', models.ImageField(blank=True, default='exercises/no_picture.jpg', null=True, upload_to=workout.models.get_photo_path, verbose_name='Картинка')),
                ('is_compound', models.BooleanField(choices=[(True, 'Базовое'), (False, 'Изолирующее')], verbose_name='Тип')),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='workout.equipment', verbose_name='Инвентарь')),
                ('level', models.ManyToManyField(blank=True, related_name='levels', to='workout.experiencelevel', verbose_name='Уровень подготовки')),
                ('muscle', models.ManyToManyField(blank=True, related_name='muscles', to='workout.targetmuscle', verbose_name='Целевая мышечная группа')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.workouttype', verbose_name='Тип тренировки')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='workout_exe_name_58701a_idx')],
            },
        ),
    ]
