# Generated by Django 4.2.1 on 2024-01-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_targetmuscle_options_remove_targetmuscle_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.workouttype', verbose_name='Тип тренировки'),
        ),
    ]
