# Generated by Django 4.2.1 on 2024-01-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercise_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.workouttype', verbose_name='Тип тренировки'),
        ),
    ]
