# Generated by Django 4.2.1 on 2024-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_exercise_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(blank=True, choices=[(True, 'Базовое'), (False, 'Изолирующее')], null=True, verbose_name='Тип'),
        ),
    ]
