# Generated by Django 4.2.1 on 2024-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/<django.db.models.query_utils.DeferredAttribute object at 0x000002875777D3F0>/', verbose_name='Photo'),
        ),
    ]
