# Generated by Django 4.2.1 on 2024-01-05 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Тренировка', max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tracker.workouttype')),
            ],
        ),
        migrations.CreateModel(
            name='SetWeightTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.exercise')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='SetStretching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(blank=True, null=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.exercise')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='SetCyclingTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.exercise')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
        ),
        migrations.CreateModel(
            name='SetAnotherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.exercise')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
        ),
    ]
