# Generated by Django 4.2.1 on 2024-01-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_workout_user_id_workout_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setanothertype',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='setanothertype',
            old_name='workout_id',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='setcyclingtraining',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='setcyclingtraining',
            old_name='workout_id',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='setstretching',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='setstretching',
            old_name='workout_id',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='setweighttraining',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='setweighttraining',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
