# Generated by Django 4.2.1 on 2024-01-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
        ('tracker', '0003_rename_exercise_id_setanothertype_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setanothertype',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='setanothertype',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='setcyclingtraining',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='setcyclingtraining',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='setstretching',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='setstretching',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='setweighttraining',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='setweighttraining',
            name='workout',
        ),
        migrations.CreateModel(
            name='ExerciseWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
        ),
        migrations.AddField(
            model_name='setanothertype',
            name='exercise_workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.exerciseworkout'),
        ),
        migrations.AddField(
            model_name='setcyclingtraining',
            name='exercise_workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.exerciseworkout'),
        ),
        migrations.AddField(
            model_name='setstretching',
            name='exercise_workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.exerciseworkout'),
        ),
        migrations.AddField(
            model_name='setweighttraining',
            name='exercise_workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.exerciseworkout'),
        ),
    ]
