# Generated by Django 4.2.1 on 2024-01-19 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_exerciseworkout_description_alter_workout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 19)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(4, 33, 44, 237702), null=True),
        ),
    ]
