# Generated by Django 4.2.1 on 2024-01-19 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_workout_date_alter_workout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(1, 37, 23, 183462), null=True),
        ),
    ]
