# Generated by Django 4.2.1 on 2024-01-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_workout_date_alter_workout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.workouttype', verbose_name='Тип тренировки'),
        ),
    ]
