# Generated by Django 4.2.1 on 2024-01-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_workout_date_alter_workout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_type',
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
    ]
