# Generated by Django 4.2.1 on 2024-01-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_workout_workout_type_delete_workouttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(default=null, on_delete=django.db.models.deletion.RESTRICT, to='tracker.workouttype', verbose_name='Тип тренировки'),
            preserve_default=False,
        ),
    ]
