# Generated by Django 4.2.1 on 2024-01-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_workout_workout_type_delete_workouttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(default='Силовая тренировка', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(default='Тренировка', max_length=100),
        ),
    ]
