# Generated by Django 4.2.1 on 2024-01-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workout.workouttype'),
        ),
    ]
