# Generated by Django 4.2.1 on 2024-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercise_workout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, default='photos/default/no_picture.jpg', null=True, upload_to='photos/<django.db.models.fields.CharField>/', verbose_name='Картинка'),
        ),
    ]
