# Generated by Django 4.2.1 on 2024-01-22 13:05

from django.db import migrations, models
import workout.models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, default='photos/default/no_picture.jpg', null=True, upload_to=workout.models.get_photo_path, verbose_name='Картинка'),
        ),
    ]
